/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.andycandy.gradle.user_input

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

import javax.swing.*

public class UserInputGradlePluginTest extends Specification {
	
    def 'plugin registers extension'() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply('de.andycandy.gradle.user_input')

        then:
        project.extensions.findByName('userInput') != null
    }
}
