/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.andycandy.gradle.user_input

import groovy.transform.CompileStatic
import org.gradle.api.Plugin
import org.gradle.api.Project

@CompileStatic
public class UserInputGradlePlugin implements Plugin<Project> {
    public void apply(Project project) {
        project.extensions.create('userInput', UserInputExtension)
    }
}
