/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package de.andycandy.gradle.user_input

import org.gradle.testkit.runner.GradleRunner
import spock.lang.Specification

public class UserInputGradlePluginFunctionalTest extends Specification {
	
    def "can define task"() {
        given:
        def projectDir = new File("build/functionalTest")
        projectDir.mkdirs()
        new File(projectDir, "settings.gradle").text = ""
        new File(projectDir, "build.gradle").text = """
            plugins {
                id('de.andycandy.gradle.user_input')
            }

			task userInput (type: de.andycandy.gradle.user_input.UserInputTask) {
			}
        """

        when:
        def runner = GradleRunner.create()
        runner.forwardOutput()
        runner.withPluginClasspath()
        runner.withArguments('tasks', '--all')
        runner.withProjectDir(projectDir)
        def result = runner.build()

        then:
        result.output.contains("userInput")
    }
}
